name: 🛡️ Security Vulnerability Report
description: Report a security vulnerability in MCP Windows Automation Server
title: "[SECURITY] "
labels: ["security", "vulnerability", "priority-high"]
assignees:
  - mukul975
body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Security Vulnerability Report
        
        **⚠️ IMPORTANT: If this is a critical security vulnerability, please consider reporting it privately via email to mukuljangra5@gmail.com instead of creating a public issue.**
        
        Thank you for helping to keep MCP Windows Automation Server secure! Please provide the following information to help us understand and address the vulnerability.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical (System compromise, remote code execution)
        - High (Privilege escalation, data exposure)
        - Medium (Limited access, information disclosure)
        - Low (Minor security impact)
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the vulnerability
      placeholder: |
        Describe the vulnerability, including:
        - What component is affected
        - What the vulnerability allows an attacker to do
        - How it could be exploited
    validations:
      required: true

  - type: textarea
    id: affected_components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - MCP Server version: 
        - Specific tools/functions:
        - Operating system:
        - Python version:
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Set up environment with...
        2. Execute command...
        3. Observe behavior...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Secure Behavior
      description: What should happen instead?
      placeholder: Describe what the secure behavior should be
    validations:
      required: true

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Who could be affected?
        - What data could be compromised?
        - What systems could be impacted?
    validations:
      required: true

  - type: textarea
    id: environment_info
    attributes:
      label: Environment Information
      description: Provide details about your environment
      placeholder: |
        - OS: Windows 10/11
        - Python version: 
        - MCP Server version:
        - Installed packages:
        - Configuration details:
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept (Optional)
      description: If safe to share, provide proof-of-concept code or screenshots
      placeholder: |
        ⚠️ Only include PoC if it's safe and doesn't enable actual attacks
        
        ```python
        # Your proof-of-concept code here
        ```
    validations:
      required: false

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix (Optional)
      description: If you have ideas for how to fix this vulnerability
      placeholder: Describe potential fixes or mitigations
    validations:
      required: false

  - type: dropdown
    id: disclosure_preference
    attributes:
      label: Disclosure Preference
      description: How would you like to handle disclosure?
      options:
        - Public disclosure after fix
        - Private disclosure preferred
        - Coordinated disclosure with timeline
        - Immediate public disclosure
    validations:
      required: true

  - type: checkboxes
    id: security_checklist
    attributes:
      label: Security Report Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this vulnerability has not already been reported
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true
        - label: I understand this will be treated as a high-priority security issue
          required: true
        - label: I agree to responsible disclosure practices
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🔒 What Happens Next?
        
        1. **Acknowledgment**: We'll respond within 24 hours
        2. **Assessment**: Initial security assessment within 72 hours
        3. **Updates**: Regular status updates during investigation
        4. **Fix**: Security fix developed and tested
        5. **Release**: Coordinated release with security advisory
        6. **Credit**: Security researcher credited (if desired)
        
        ## 📞 Emergency Contact
        
        For critical vulnerabilities requiring immediate attention:
        - **Email**: mukuljangra5@gmail.com
        - **Response**: Within 2 hours during business hours
        
        Thank you for helping to keep MCP Windows Automation Server secure! 🛡️
